import { AgentRecord } from '../types';

export const SEED_AGENTS: AgentRecord[] = [
  // 1. High Trust - Verified MCP Anthropic Git Server
  {
    id: 'agent-mcp-git',
    name: 'Git MCP Server (Official)',
    slug: 'modelcontextprotocol/server-git',
    description: 'Official Model Context Protocol server providing secure Git repository reading, diff inspection, and commit staging capabilities.',
    category: 'coding',
    sourceEcosystem: 'mcp_registry',
    publisher: {
      name: 'Model Context Protocol Core',
      domain: 'modelcontextprotocol.io',
      verifiedDomain: true,
      identityType: 'verified_org',
      githubUser: 'modelcontextprotocol',
      reputationScore: 98,
    },
    framework: 'mcp',
    repositoryUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/git',
    packageUrl: 'https://www.npmjs.com/package/@modelcontextprotocol/server-git',
    declaredCapabilities: ['git_read', 'diff_analysis', 'commit_staging'],
    requestedPermissions: [
      { scope: 'git:read', sensitivity: 'low', justification: 'Inspect repository commits, branches, and diffs.' },
      { scope: 'git:commit', sensitivity: 'medium', justification: 'Stage and commit changes on user command.' },
    ],
    toolsDeclared: [
      { name: 'git_status', description: 'Show status of working directory', parameters: {} },
      { name: 'git_diff', description: 'Show changes between commits or working tree', parameters: { cached: 'boolean' } },
      { name: 'git_commit', description: 'Record changes to the repository', parameters: { message: 'string' }, requiresApproval: true },
    ],
    externalConnections: [],
    hasAuditLogs: true,
    requiresHumanApproval: true,
    isSandboxed: true,
    hasPromptInjectionGuard: true,
    hasKnownCVEs: false,
    cveCount: 0,
    hasMalwareHistory: false,
    hasCredentialStealRisk: false,
    starsCount: 6500,
    forksCount: 920,
    monthlyUsers: 120000,
    lastCommitDate: '2026-08-30T16:00:00Z',
    discoveredAt: '2026-08-15T10:00:00Z',
    fingerprint: {
      fingerprintId: 'fp-mcp-git-001',
      timestamp: '2026-08-30T16:00:00Z',
      manifestHash: 'sha256:git_manifest_v1',
      toolSchemasHash: 'sha256:git_tools_v1',
      permissionsHash: 'sha256:git_perms_v1',
      dependenciesHash: 'sha256:git_deps_v1',
      isDriftDetected: false,
    },
  },

  // 2. High Trust - Deep Research Agent (GitHub)
  {
    id: 'agent-deep-research',
    name: 'OpenDeepResearch Agent',
    slug: 'open-research-lab/deep-researcher',
    description: 'Autonomous multi-step research synthesis agent that gathers academic papers, verifies citations, and produces structured markdown reports.',
    category: 'research',
    sourceEcosystem: 'github',
    publisher: {
      name: 'Open Research Institute',
      domain: 'openresearch.org',
      verifiedDomain: true,
      identityType: 'verified_org',
      githubUser: 'openresearch-org',
      reputationScore: 94,
    },
    framework: 'langchain',
    repositoryUrl: 'https://github.com/openresearch-org/deep-researcher',
    declaredCapabilities: ['web_search', 'arxiv_api_read', 'citation_graph'],
    requestedPermissions: [
      { scope: 'network:outbound_https', sensitivity: 'low', justification: 'Fetch research papers and public scientific literature.' },
      { scope: 'fs:workspace_write', sensitivity: 'medium', justification: 'Save output markdown reports to user workspace.' },
    ],
    toolsDeclared: [
      { name: 'search_arxiv', description: 'Query ArXiv API for papers', parameters: { query: 'string' } },
      { name: 'fetch_paper_pdf', description: 'Download and parse PDF text', parameters: { arxiv_id: 'string' } },
    ],
    externalConnections: ['export.arxiv.org', 'api.semanticscholar.org'],
    hasAuditLogs: true,
    requiresHumanApproval: false,
    isSandboxed: true,
    hasPromptInjectionGuard: true,
    hasKnownCVEs: false,
    cveCount: 0,
    hasMalwareHistory: false,
    hasCredentialStealRisk: false,
    starsCount: 8900,
    forksCount: 1400,
    monthlyUsers: 78000,
    lastCommitDate: '2026-08-25T11:00:00Z',
    discoveredAt: '2026-08-10T12:00:00Z',
    fingerprint: {
      fingerprintId: 'fp-deep-research-002',
      timestamp: '2026-08-25T11:00:00Z',
      manifestHash: 'sha256:research_manifest_v1',
      toolSchemasHash: 'sha256:research_tools_v1',
      permissionsHash: 'sha256:research_perms_v1',
      dependenciesHash: 'sha256:research_deps_v1',
      isDriftDetected: false,
    },
  },

  // 3. High Trust - CrewAI Lead Finder
  {
    id: 'agent-crewai-lead-finder',
    name: 'CrewAI B2B Lead Researcher',
    slug: 'crewai-hub/lead-finder-agent',
    description: 'Enterprise multi-agent pipeline researching verified B2B prospects and synthesizing company public profiles.',
    category: 'sales_marketing',
    sourceEcosystem: 'agent_marketplace',
    publisher: {
      name: 'CrewAI Verified Hub',
      domain: 'crewai.com',
      verifiedDomain: true,
      identityType: 'verified_org',
      reputationScore: 92,
    },
    framework: 'crewai',
    repositoryUrl: 'https://github.com/crewAIInc/crewAI-examples',
    packageUrl: 'https://pypi.org/project/crewai-tools/',
    declaredCapabilities: ['web_scraping', 'crm_data_enrichment', 'llm_synthesis'],
    requestedPermissions: [
      { scope: 'network:outbound_https', sensitivity: 'low', justification: 'Scrape public corporate web pages.' },
      { scope: 'crm:contacts_read', sensitivity: 'medium', justification: 'Enrich existing sales pipelines.' },
    ],
    toolsDeclared: [
      { name: 'scrape_company_site', description: 'Scrape text from website', parameters: { url: 'string' } },
      { name: 'enrich_prospect', description: 'Query Clearbit API', parameters: { domain: 'string' } },
    ],
    externalConnections: ['api.clearbit.com', 'api.openai.com'],
    hasAuditLogs: true,
    requiresHumanApproval: true,
    isSandboxed: true,
    hasPromptInjectionGuard: true,
    hasKnownCVEs: false,
    cveCount: 0,
    hasMalwareHistory: false,
    hasCredentialStealRisk: false,
    starsCount: 18500,
    forksCount: 2900,
    monthlyUsers: 45000,
    lastCommitDate: '2026-08-29T14:30:00Z',
    discoveredAt: '2026-08-01T09:00:00Z',
    fingerprint: {
      fingerprintId: 'fp-crewai-leads-441',
      timestamp: '2026-08-29T14:30:00Z',
      manifestHash: 'sha256:crew_leads_v1',
      toolSchemasHash: 'sha256:crew_leads_tools_v1',
      permissionsHash: 'sha256:crew_leads_perms_v1',
      dependenciesHash: 'sha256:crew_leads_deps_v1',
      isDriftDetected: false,
    },
  },

  // 4. Medium Trust - Smart Calendar Butler (Scope Warning)
  {
    id: 'agent-autocalendar-ai',
    name: 'Smart Calendar Butler Pro',
    slug: 'nexus-labs/smart-calendar-butler',
    description: 'AI scheduling assistant that coordinates meetings, drafts calendar invites, and organizes your daily schedule.',
    category: 'productivity',
    sourceEcosystem: 'agent_marketplace',
    publisher: {
      name: 'Nexus Productivity Labs',
      domain: 'nexusproductivity.io',
      verifiedDomain: false,
      identityType: 'individual',
      reputationScore: 68,
    },
    framework: 'langchain',
    websiteUrl: 'https://smartcalendar-demo.io',
    declaredCapabilities: ['calendar_coordination', 'email_monitoring'],
    requestedPermissions: [
      { scope: 'calendar:read_write', sensitivity: 'medium', justification: 'Create and update calendar events.' },
      { scope: 'gmail:read_all', sensitivity: 'high', isHighRisk: true, justification: 'Scan all incoming emails for scheduling requests.' },
      { scope: 'gdrive:read_all', sensitivity: 'high', isHighRisk: true, justification: 'Check meeting attachments in Google Drive.' },
    ],
    toolsDeclared: [
      { name: 'list_events', description: 'Fetch calendar appointments', parameters: { days: 'number' } },
      { name: 'search_emails', description: 'Search full email inbox', parameters: { query: 'string' } },
    ],
    externalConnections: ['api.nexusproductivity.io', 'googleapis.com'],
    hasAuditLogs: false,
    requiresHumanApproval: false,
    isSandboxed: false,
    hasPromptInjectionGuard: false,
    hasKnownCVEs: false,
    cveCount: 0,
    hasMalwareHistory: false,
    hasCredentialStealRisk: false,
    starsCount: 140,
    monthlyUsers: 1200,
    lastCommitDate: '2026-07-15T09:00:00Z',
    discoveredAt: '2026-07-10T14:00:00Z',
    fingerprint: {
      fingerprintId: 'fp-autocalendar-212',
      timestamp: '2026-07-15T09:00:00Z',
      manifestHash: 'sha256:cal_butler_v1',
      toolSchemasHash: 'sha256:cal_butler_tools_v1',
      permissionsHash: 'sha256:cal_butler_perms_v1',
      dependenciesHash: 'sha256:cal_butler_deps_v1',
      isDriftDetected: false,
    },
  },

  // 5. Medium Trust - DevSecOps Triage Agent
  {
    id: 'agent-devsecops-triage',
    name: 'DevSecOps Sentry Bot',
    slug: 'cloudguard-security/devsecops-sentry',
    description: 'Automated CI/CD security reviewer that analyzes pull request code diffs for secrets and insecure dependencies.',
    category: 'coding',
    sourceEcosystem: 'github',
    publisher: {
      name: 'CloudGuard Security',
      domain: 'cloudguard.dev',
      verifiedDomain: true,
      identityType: 'verified_org',
      githubUser: 'cloudguard-security',
      reputationScore: 78,
    },
    framework: 'autogen',
    repositoryUrl: 'https://github.com/cloudguard-security/devsecops-sentry',
    declaredCapabilities: ['pr_review', 'ast_scanning', 'secret_detection'],
    requestedPermissions: [
      { scope: 'github:pr_write', sensitivity: 'medium', justification: 'Post security review comments on GitHub pull requests.' },
      { scope: 'github:repo_read', sensitivity: 'low', justification: 'Read repository files and git log.' },
    ],
    toolsDeclared: [
      { name: 'scan_diff', description: 'Analyze PR patch for high-entropy secrets', parameters: { patch: 'string' } },
      { name: 'post_comment', description: 'Post review comment to GitHub PR', parameters: { pr_id: 'number', comment: 'string' } },
    ],
    externalConnections: ['api.github.com', 'telemetry.cloudguard.dev'],
    hasAuditLogs: true,
    requiresHumanApproval: false,
    isSandboxed: true,
    hasPromptInjectionGuard: false,
    hasKnownCVEs: true,
    cveCount: 1, // 1 low severity CVE
    hasMalwareHistory: false,
    hasCredentialStealRisk: false,
    starsCount: 620,
    forksCount: 88,
    monthlyUsers: 4500,
    lastCommitDate: '2026-08-18T10:00:00Z',
    discoveredAt: '2026-08-01T15:00:00Z',
    fingerprint: {
      fingerprintId: 'fp-devsec-909',
      timestamp: '2026-08-18T10:00:00Z',
      manifestHash: 'sha256:devsec_manifest_v1',
      toolSchemasHash: 'sha256:devsec_tools_v1',
      permissionsHash: 'sha256:devsec_perms_v1',
      dependenciesHash: 'sha256:devsec_deps_v1',
      isDriftDetected: false,
    },
  },

  // 6. High Risk - Shadow Commander Shell Tool (Unsandboxed shell execution)
  {
    id: 'agent-mcp-shadow-commander',
    name: 'Shadow Commander Shell Tool',
    slug: 'ghostsec-anon/mcp-shell-commander',
    description: 'MCP server tool advertising terminal execution shortcuts with unconstrained root access.',
    category: 'sysadmin',
    sourceEcosystem: 'mcp_registry',
    publisher: {
      name: 'GhostSec Anon',
      domain: undefined,
      verifiedDomain: false,
      identityType: 'anonymous',
      reputationScore: 28,
    },
    framework: 'mcp',
    repositoryUrl: 'https://github.com/ghostsec-anon/mcp-shell-commander',
    declaredCapabilities: ['arbitrary_bash_execution', 'file_manipulation'],
    requestedPermissions: [
      { scope: 'terminal:root_exec', sensitivity: 'critical', isHighRisk: true, justification: 'Execute raw shell command on host machine.' },
      { scope: 'fs:root_write', sensitivity: 'critical', isHighRisk: true, justification: 'Modify system root directories.' },
    ],
    toolsDeclared: [
      { name: 'exec_bash', description: 'Run raw shell script with root rights', parameters: { cmd: 'string' } },
      { name: 'dump_proc', description: 'Dump system process table', parameters: {} },
    ],
    externalConnections: ['185.196.220.14', 'telemetry.ghostsec.cc'],
    hasAuditLogs: false,
    requiresHumanApproval: false, // Critical vulnerability trigger!
    isSandboxed: false, // Critical vulnerability trigger!
    hasPromptInjectionGuard: false,
    hasKnownCVEs: true,
    cveCount: 3,
    hasMalwareHistory: false,
    hasCredentialStealRisk: true,
    starsCount: 14,
    forksCount: 2,
    lastCommitDate: '2026-09-01T04:00:00Z',
    discoveredAt: '2026-09-01T04:00:00Z',
    fingerprint: {
      fingerprintId: 'fp-mcp-shadow-00x',
      timestamp: '2026-09-01T04:00:00Z',
      manifestHash: 'sha256:shadow_manifest_v2',
      toolSchemasHash: 'sha256:shadow_tools_v2',
      permissionsHash: 'sha256:shadow_perms_v2',
      dependenciesHash: 'sha256:shadow_deps_v2',
      isDriftDetected: true,
      lastDriftTimestamp: '2026-09-01T04:00:00Z',
    },
  },

  // 7. Critical Risk - AlphaSniper Crypto Bot (Confirmed Malware & Credential Theft)
  {
    id: 'agent-crypto-sniper',
    name: 'AlphaSniper DEX Agent',
    slug: 'solana-tools/alpha-sniper-bot',
    description: 'High-speed automated crypto trading agent designed to monitor Telegram signals and execute instant decentralized exchange swaps.',
    category: 'finance',
    sourceEcosystem: 'agent_marketplace',
    publisher: {
      name: 'AnonTrader99',
      domain: undefined,
      verifiedDomain: false,
      identityType: 'anonymous',
      reputationScore: 19,
    },
    framework: 'custom',
    websiteUrl: 'https://t.me/alphasniper_bot',
    declaredCapabilities: ['telegram_scraping', 'wallet_signing', 'dex_swap_execution'],
    requestedPermissions: [
      { scope: 'wallet:private_key_export', sensitivity: 'critical', isHighRisk: true, justification: 'Import private key to sign rapid transactions.' },
      { scope: 'telegram:messages_read_write', sensitivity: 'high', justification: 'Read signals from private Telegram channels.' },
    ],
    toolsDeclared: [
      { name: 'import_key', description: 'Store wallet private seed in local cache', parameters: { private_key: 'string' } },
      { name: 'execute_swap', description: 'Send automated transaction on DEX router', parameters: { amount: 'number' } },
    ],
    externalConnections: ['api.telegram.org', '194.26.29.11', 'raw.githubusercontent.com'],
    hasAuditLogs: false,
    requiresHumanApproval: false,
    isSandboxed: false,
    hasPromptInjectionGuard: false,
    hasKnownCVEs: true,
    cveCount: 4,
    hasMalwareHistory: true, // Malicious override trigger!
    hasCredentialStealRisk: true, // Malicious override trigger!
    starsCount: 22,
    lastCommitDate: '2026-09-02T18:00:00Z',
    discoveredAt: '2026-09-02T18:00:00Z',
    fingerprint: {
      fingerprintId: 'fp-crypto-sniper-666',
      timestamp: '2026-09-02T18:00:00Z',
      manifestHash: 'sha256:malware_sniper_v1',
      toolSchemasHash: 'sha256:malware_sniper_tools',
      permissionsHash: 'sha256:malware_sniper_perms',
      dependenciesHash: 'sha256:malware_sniper_deps',
      isDriftDetected: true,
      lastDriftTimestamp: '2026-09-02T18:00:00Z',
    },
  },

  // 8. High Trust - Anthropic Brave Search MCP
  {
    id: 'agent-mcp-brave-search',
    name: 'Brave Search MCP Agent',
    slug: 'modelcontextprotocol/server-brave-search',
    description: 'Official Model Context Protocol server providing web queries and local business retrieval through Brave Search API.',
    category: 'research',
    sourceEcosystem: 'mcp_registry',
    publisher: {
      name: 'Model Context Protocol Core',
      domain: 'modelcontextprotocol.io',
      verifiedDomain: true,
      identityType: 'verified_org',
      githubUser: 'modelcontextprotocol',
      reputationScore: 95,
    },
    framework: 'mcp',
    repositoryUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search',
    packageUrl: 'https://www.npmjs.com/package/@modelcontextprotocol/server-brave-search',
    declaredCapabilities: ['web_search', 'local_poi_search'],
    requestedPermissions: [
      { scope: 'network:outbound_https', sensitivity: 'low', justification: 'Make REST requests to api.search.brave.com' },
    ],
    toolsDeclared: [
      { name: 'brave_web_search', description: 'Execute web query', parameters: { query: 'string', count: 'number' } },
    ],
    externalConnections: ['api.search.brave.com'],
    hasAuditLogs: true,
    requiresHumanApproval: false,
    isSandboxed: true,
    hasPromptInjectionGuard: true,
    hasKnownCVEs: false,
    cveCount: 0,
    hasMalwareHistory: false,
    hasCredentialStealRisk: false,
    starsCount: 3800,
    forksCount: 490,
    monthlyUsers: 64000,
    lastCommitDate: '2026-08-20T10:00:00Z',
    discoveredAt: '2026-08-10T10:00:00Z',
    fingerprint: {
      fingerprintId: 'fp-mcp-brave-88b',
      timestamp: '2026-08-20T10:00:00Z',
      manifestHash: 'sha256:44bcd82a1d22',
      toolSchemasHash: 'sha256:mcp_brave_tools_v1',
      permissionsHash: 'sha256:mcp_brave_perms_v1',
      dependenciesHash: 'sha256:mcp_brave_deps_v1',
      isDriftDetected: false,
    },
  },
];
