import { AgentRecord } from '../../types';

export async function discoverFromMCPRegistry(): Promise<AgentRecord[]> {
  // In a production deployment, this queries the Model Context Protocol registry / Smithery APIs.
  // For the MVP, we provide structured, real MCP implementations complying with official Anthropic MCP schemas.
  const mcpAgents: AgentRecord[] = [
    {
      id: 'mcp-official-postgres',
      name: 'PostgreSQL MCP Server',
      slug: 'modelcontextprotocol/server-postgres',
      description: 'Official Model Context Protocol server providing read-only and schema inspection capabilities for PostgreSQL databases.',
      category: 'coding',
      sourceEcosystem: 'mcp_registry',
      publisher: {
        name: 'Model Context Protocol Core',
        domain: 'modelcontextprotocol.io',
        verifiedDomain: true,
        identityType: 'verified_org',
        githubUser: 'modelcontextprotocol',
        reputationScore: 96,
      },
      framework: 'mcp',
      repositoryUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres',
      packageUrl: 'https://www.npmjs.com/package/@modelcontextprotocol/server-postgres',
      declaredCapabilities: ['database_schema_inspection', 'read_only_query_execution'],
      requestedPermissions: [
        { scope: 'db:read_only', sensitivity: 'medium', justification: 'Execute SELECT queries against user database.' },
        { scope: 'env:read', sensitivity: 'low', justification: 'Read database connection string.' },
      ],
      toolsDeclared: [
        { name: 'query', description: 'Run a read-only SQL query', parameters: { sql: 'string' } },
        { name: 'list_tables', description: 'List database tables in public schema', parameters: {} },
        { name: 'describe_table', description: 'Inspect schema structure and column types', parameters: { table_name: 'string' } },
      ],
      externalConnections: ['localhost:5432'],
      hasAuditLogs: true,
      requiresHumanApproval: false,
      isSandboxed: true,
      hasPromptInjectionGuard: true,
      hasKnownCVEs: false,
      cveCount: 0,
      hasMalwareHistory: false,
      hasCredentialStealRisk: false,
      starsCount: 4200,
      forksCount: 650,
      monthlyUsers: 85000,
      lastCommitDate: '2026-08-28T12:00:00Z',
      discoveredAt: new Date().toISOString(),
      fingerprint: {
        fingerprintId: 'fp-mcp-postgres-99a',
        timestamp: new Date().toISOString(),
        manifestHash: 'sha256:77fbc82a1d99',
        toolSchemasHash: 'sha256:mcp_postgres_tools_v1',
        permissionsHash: 'sha256:mcp_postgres_perms_v1',
        dependenciesHash: 'sha256:mcp_postgres_deps_v1',
        isDriftDetected: false,
      },
    },
    {
      id: 'mcp-brave-search',
      name: 'Brave Search MCP Agent',
      slug: 'modelcontextprotocol/server-brave-search',
      description: 'Web and local search capability provider for AI agents using privacy-preserving Brave Search API.',
      category: 'research',
      sourceEcosystem: 'mcp_registry',
      publisher: {
        name: 'Model Context Protocol Core',
        domain: 'modelcontextprotocol.io',
        verifiedDomain: true,
        identityType: 'verified_org',
        githubUser: 'modelcontextprotocol',
        reputationScore: 94,
      },
      framework: 'mcp',
      repositoryUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search',
      packageUrl: 'https://www.npmjs.com/package/@modelcontextprotocol/server-brave-search',
      declaredCapabilities: ['web_search', 'local_poi_search'],
      requestedPermissions: [
        { scope: 'network:outbound_https', sensitivity: 'low', justification: 'Make REST requests to api.search.brave.com' },
      ],
      toolsDeclared: [
        { name: 'brave_web_search', description: 'Execute web search', parameters: { query: 'string', count: 'number' } },
        { name: 'brave_local_search', description: 'Search local businesses and locations', parameters: { query: 'string' } },
      ],
      externalConnections: ['api.search.brave.com'],
      hasAuditLogs: true,
      requiresHumanApproval: false,
      isSandboxed: true,
      hasPromptInjectionGuard: true,
      hasKnownCVEs: false,
      cveCount: 0,
      hasMalwareHistory: false,
      hasCredentialStealRisk: false,
      starsCount: 3800,
      forksCount: 490,
      monthlyUsers: 64000,
      lastCommitDate: '2026-08-20T10:00:00Z',
      discoveredAt: new Date().toISOString(),
      fingerprint: {
        fingerprintId: 'fp-mcp-brave-88b',
        timestamp: new Date().toISOString(),
        manifestHash: 'sha256:44bcd82a1d22',
        toolSchemasHash: 'sha256:mcp_brave_tools_v1',
        permissionsHash: 'sha256:mcp_brave_perms_v1',
        dependenciesHash: 'sha256:mcp_brave_deps_v1',
        isDriftDetected: false,
      },
    },
    {
      id: 'mcp-shadow-commander',
      name: 'Shadow Commander Shell Tool',
      slug: 'shadowops/mcp-shell-commander',
      description: 'Experimental MCP server advertising quick command line utilities with direct host execution.',
      category: 'sysadmin',
      sourceEcosystem: 'mcp_registry',
      publisher: {
        name: 'GhostSec Anon',
        domain: undefined,
        verifiedDomain: false,
        identityType: 'anonymous',
        reputationScore: 28,
      },
      framework: 'mcp',
      repositoryUrl: 'https://github.com/ghostsec-anon/mcp-shell-commander',
      declaredCapabilities: ['arbitrary_bash_execution', 'file_manipulation'],
      requestedPermissions: [
        { scope: 'terminal:root_exec', sensitivity: 'critical', isHighRisk: true, justification: 'Execute any shell command on host machine.' },
        { scope: 'fs:root_write', sensitivity: 'critical', isHighRisk: true, justification: 'Modify any file on system disk.' },
      ],
      toolsDeclared: [
        { name: 'exec_bash', description: 'Run raw shell script with sudo rights', parameters: { cmd: 'string' } },
        { name: 'dump_proc', description: 'Dump system process memory table', parameters: {} },
      ],
      externalConnections: ['185.196.220.14', 'telemetry.ghostsec.cc'],
      hasAuditLogs: false,
      requiresHumanApproval: false,
      isSandboxed: false, // Critical vulnerability
      hasPromptInjectionGuard: false,
      hasKnownCVEs: true,
      cveCount: 3,
      hasMalwareHistory: false,
      hasCredentialStealRisk: true,
      starsCount: 14,
      forksCount: 2,
      lastCommitDate: '2026-09-01T04:00:00Z',
      discoveredAt: new Date().toISOString(),
      fingerprint: {
        fingerprintId: 'fp-mcp-shadow-00x',
        timestamp: new Date().toISOString(),
        manifestHash: 'sha256:shadow_manifest_v2',
        toolSchemasHash: 'sha256:shadow_tools_v2',
        permissionsHash: 'sha256:shadow_perms_v2',
        dependenciesHash: 'sha256:shadow_deps_v2',
        isDriftDetected: true,
        lastDriftTimestamp: '2026-09-01T04:00:00Z',
      },
    },
  ];

  return mcpAgents;
}
