import Link from 'next/link';
import { redirect } from 'next/navigation';
import { ArrowRight, Check, FileCheck2, Fingerprint, Workflow } from 'lucide-react';
import { IntentDemo } from '@/components/marketing/IntentDemo';
import { ProviderFlow } from '@/components/marketing/ProviderFlow';

export default function MarketingHome({ searchParams }: { searchParams: { tab?: string; q?: string; code?: string } }) {
  const params = new URLSearchParams();
  if (searchParams.tab) params.set('tab', searchParams.tab);
  if (searchParams.q) params.set('q', searchParams.q);
  if (searchParams.code) params.set('code', searchParams.code);
  if (params.size) redirect(`/app?${params.toString()}`);
  return <main id="content">
    <section className="marketing-hero"><div className="hero-copy"><h1>Agent-powered finance.<br /><span>Human intent,<br />intact.</span></h1><p>Verify that every agent purchase matches what you actually asked. Bring intent authorization to the financial workflows you already use.</p><div className="marketing-actions"><Link href="/contact" className="marketing-button">Request a demo <ArrowRight size={18} /></Link><Link href="/demo" className="text-link">See how it works <ArrowRight size={18} /></Link></div><div className="hero-platforms"><span>Designed for workflows with</span><div>Brex <i>/</i> Ramp <i>/</i> Slash</div><small>One platform or several. Integrations planned.</small></div></div><div className="hero-product"><IntentDemo compact /></div></section>
    <section id="product" className="product-story"><div><h2>Within budget.<br />Outside your intent.</h2><p>A $19,900 purchase can meet your spending limit and still buy ten laptops you never asked for. TRUSTY checks the action against the original mandate, before the workflow proceeds.</p><Link href="/demo" className="text-link">Try the 20-laptop example <ArrowRight size={18} /></Link></div><div className="intent-comparison"><div><span>What you asked for</span><strong>20 laptops</strong><p>16 GB RAM · Miami office</p></div><div><span>What the agent prepared</span><strong>30 laptops</strong><p>$19,900 · Within the $20,000 limit</p></div><p><FileCheck2 size={21} /> TRUSTY flags the quantity mismatch for human review.</p></div></section>
    <section className="workflow-section"><h2>From “take care of it”<br />to a decision you can explain.</h2><div className="workflow-steps">{[{ icon: Fingerprint, title: 'Define the mandate', text: 'Turn the original instruction into confirmed quantities, specifications, limits and delivery requirements.' }, { icon: Workflow, title: 'Inspect the action', text: 'Compare the proposed cart with each requirement. Surface mismatches and missing evidence for review.' }, { icon: FileCheck2, title: 'Keep the proof', text: 'Connect the instruction, proposed action and decision. Add the observed outcome when the workflow is integrated.' }].map(({icon: Icon, title, text}) => <article key={title}><Icon size={30} strokeWidth={1.4} /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="integrations" className="integration-section"><div><h2>Your financial stack.<br />A shared layer of intent.</h2><p>Use Brex alone? Start there. Use Brex and Ramp? Apply the same mandate checks to both workflows as connections become available.</p><p>Your financial platforms keep their native spending controls. TRUSTY adds context about what the human authorized.</p><ul><li><Check size={18} /> Start with a single purchasing workflow</li><li><Check size={18} /> Retain your provider’s financial controls</li><li><Check size={18} /> Expand coverage as your operations grow</li></ul><Link href="/docs" className="text-link">Explore the integration approach <ArrowRight size={18} /></Link></div><ProviderFlow /></section>
    <section id="pilot" className="pilot-section"><div><h2>Start with one workflow.<br />Build the evidence together.</h2><p>A 30-day design partner pilot for teams bringing agents into procurement. Begin in observation mode and move to limited controls after validation.</p><Link href="/contact" className="marketing-button">Explore a pilot <ArrowRight size={18} /></Link></div><ol><li><span>Week 1</span><strong>Connect the workflow</strong><p>Define the mandate and purchase evidence.</p></li><li><span>Week 2</span><strong>Observe decisions</strong><p>Compare intent checks with human approvals.</p></li><li><span>Week 3</span><strong>Introduce limited controls</strong><p>Review mismatches within an agreed scope.</p></li><li><span>Week 4</span><strong>Measure what changed</strong><p>Review confirmed deviations, effort and evidence.</p></li></ol></section>
    <section className="marketing-close"><h2>Let agents move work forward.<br />Keep the mandate yours.</h2><Link href="/contact" className="marketing-button">Request a demo <ArrowRight size={18} /></Link><Link href="/app" className="text-link">Already exploring? Open the app <ArrowRight size={18} /></Link></section>
  </main>;
}
